const fs=require('node:fs'),path=require('node:path');
const base=fs.readFileSync(path.join(__dirname,'t11-browser.cjs'),'utf8');
let prefix=base.slice(0,base.indexOf("if(phase==='red'){")).replaceAll('t11-','t14-');
prefix=prefix.replace("controlled:!local}","controlled:!local,path:u.pathname,body:p.request.postData}");
prefix=prefix.replace("const wfs=u.pathname.endsWith('/ows');send", "const wfs=u.pathname.endsWith('/ows'),rest=u.pathname==='/buscar_direccion';send");
prefix=prefix.replace("value:wfs?'application/json':'image/png'", "value:wfs||rest?'application/json':'image/png'");
prefix=prefix.replace("{name:'Access-Control-Allow-Origin',value:'*'}", "{name:'Access-Control-Allow-Origin',value:'*'},{name:'Access-Control-Allow-Headers',value:'Content-Type'},{name:'Access-Control-Allow-Methods',value:'GET,POST,OPTIONS'}");
prefix=prefix.replace("body:wfs?Buffer.from", "body:rest?Buffer.from(global.responseBody||'{\"latitud\":-35,\"longitud\":-58}').toString('base64'):wfs?Buffer.from");
const body=String.raw`
 const open=async mobile=>{if(mobile)await evaluate('document.querySelector(".mobile-menu-toggle").click()');await evaluate('window.trigger=document.querySelector("'+(mobile?'.mobile-nav-buttons':'.nav-buttons')+' button");trigger.click()');await delay(400);};
 const measure=()=>evaluate('(()=>{const rect=e=>{let r=e.getBoundingClientRect(),s=getComputedStyle(e);return {width:r.width,height:r.height,color:s.color,bg:s.backgroundColor,border:s.borderTopColor,outline:s.outlineColor,outlineWidth:s.outlineWidth,font:s.fontSize}};return {viewport:[innerWidth,innerHeight],theme:document.documentElement.dataset.theme,surface:rect(document.querySelector(".modal-content")),label:rect(document.querySelector(".input-group label")),input:rect(document.getElementById("direccion-input")),button:rect(document.querySelector(".btn-primary")),close:rect(document.querySelector(".close-button")),placeholder:getComputedStyle(document.getElementById("direccion-input"),"::placeholder").color,header:document.querySelector(".modal-header").getBoundingClientRect().height}})()');
 const lum=c=>{const a=c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4});return a[0]*.2126+a[1]*.7152+a[2]*.0722};const ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
 await evaluate('document.documentElement.dataset.theme="dark"');await open(false);let m=await measure();evidence.measurements.push(m);
 if(phase==='red'){assert.notEqual(m.surface.bg,'rgb(255, 255, 255)','Superficie permanece blanca en oscuro');throw Error('Rojo inesperadamente pasa');}
 await evaluate('document.querySelector(".close-button").click()');
 for(const [w,h] of [[360,800],[800,360],[768,1024],[1366,768]])for(const theme of ['light','dark']){
  await viewport(w,h);await evaluate('document.documentElement.dataset.theme="'+theme+'"');await open(w<=768);const m=await measure();m.ratios={label:ratio(m.label.color,m.surface.bg),input:ratio(m.input.color,m.input.bg),placeholder:ratio(m.placeholder,m.input.bg),border:ratio(m.input.border,m.input.bg),button:ratio(m.button.color,m.button.bg),close:ratio(m.close.color,m.surface.bg)};evidence.measurements.push(m);
  for(const [k,v] of Object.entries(m.ratios))assert(v>=(k==='border'?3:4.5),k+': '+v);assert(m.header<=48);
  await evaluate('document.querySelector(".close-button").focus()');await key('Tab','Tab',9);assert.equal(await evaluate('document.activeElement.id'),'direccion-input');let f=await measure();assert.equal(f.input.outlineWidth,'3px');assert(ratio(f.input.outline,f.input.bg)>=3);await key('Tab','Tab',9);assert.equal(await evaluate('document.activeElement.classList.contains("btn-primary")'),true);f=await measure();assert.equal(f.button.outlineWidth,'3px');assert(ratio(f.button.outline,f.surface.bg)>=3);await key('Tab','Tab',9,8);assert.equal(await evaluate('document.activeElement.id'),'direccion-input');
  const shot=await send('Page.captureScreenshot',{format:'png'});writeFileSync(join(__dirname,'t14-'+w+'-'+theme+'.png'),Buffer.from(shot.data,'base64'));
  await evaluate('document.querySelector(".close-button").click()');
 }
 evidence.checks.push('Cuatro viewports ambos temas: contraste texto/placeholder/Buscar/cierre >=4.5, borde/foco >=3; Tab/Mayús+Tab y header <=48');
 await viewport(1366,768);
 const dialogs=[];const prev=ws.onmessage;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Page.javascriptDialogOpening'){dialogs.push(m.params.message);send('Page.handleJavaScriptDialog',{accept:true});}prev(e);};
 const fill=async value=>evaluate('(()=>{let i=document.getElementById("direccion-input");i.value='+JSON.stringify(value)+';i.dispatchEvent(new Event("input",{bubbles:true}));i.focus()})()');
 for(const action of ['Enter','Buscar','keyboard']){await open(false);await fill('  CALLE FICTICIA 100  ');const before=evidence.requests.filter(r=>r.method==='POST').length;if(action==='Enter')await key('Enter','Enter',13);else if(action==='Buscar')await evaluate('document.querySelector(".btn-primary").click()');else{await key('Tab','Tab',9);await key('Enter','Enter',13);}await delay(500);const posts=evidence.requests.filter(r=>r.method==='POST');assert.equal(posts.length,before+1);assert.equal(posts.at(-1).path,'/buscar_direccion');assert.deepEqual(JSON.parse(posts.at(-1).body),{direccion:'CALLE FICTICIA 100'});assert(posts.at(-1).controlled);assert.equal(await evaluate('!!document.querySelector(".modal-content")'),false);assert.equal(await evaluate('document.activeElement===trigger'),true);}
 evidence.checks.push('Enter campo, clic Buscar y Enter botón: exactamente un POST controlado /buscar_direccion, dirección trim exacta, cierre/retorno conservados');
 await open(false);await fill('   ');await key('Enter','Enter',13);await evaluate('document.querySelector(".btn-primary").click()');assert.deepEqual(dialogs,['Por favor, ingrese una dirección.','Por favor, ingrese una dirección.']);assert.equal(await evaluate('!!document.querySelector(".modal-content")'),true);await evaluate('document.querySelector(".close-button").click()');
 global.responseBody='{}';await open(false);await fill('CALLE FICTICIA 100');await key('Enter','Enter',13);await delay(400);assert.equal(dialogs.at(-1),'No se recibieron coordenadas válidas del backend.');
 global.responseBody='invalid';await open(false);await fill('CALLE FICTICIA 100');await key('Enter','Enter',13);await delay(400);assert.match(dialogs.at(-1),/^Error al buscar dirección: /);evidence.alerts=dialogs;evidence.checks.push('Alertas nativas: vacío Enter/Buscar, coordenadas ausentes y catch; disparadores y textos conservados');
 assert.deepEqual(evidence.errors,[]);assert(evidence.requests.every(r=>r.method==='GET'||r.controlled));evidence.checks.push('Cero excepciones/logs de error CDP; externos interceptados antes de navegar, ninguna escritura real');evidence.result='pasa';await send('Browser.close');
`;
const tail=base.slice(base.indexOf('})().catch')).replaceAll('t11-','t14-').replace('header:m.nav.height','header:m.header');
eval(prefix.replace('const measure=', 'const oldMeasure=').replace("type:'keyDown'", "type:'rawKeyDown'").replace("...(key==='Enter'?{text:'\\r'}:{})", "")+body+tail);
